[project]
name = "03-coding-assistant"
version = "0.1.0"
description = "Code Assistant Agent: Introducing the Next-Generation Coding Sidekick"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "strands-agents>=0.0.1",
    "strands-agents-tools>=0.0.1",
]
